channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - gsl
  - numpy
  - scipy
  - wurlitzer
  - six
  - pip
  - pip:
    - colossus
    - ipython==7.16.1
    - nbsphinx
    - nbsphinx_link